// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8bCKbMmjkQSTuQAyeUlbi6trYeimPhZQ',
    appId: '1:480367101608:web:5a52d7e37da605c116649d',
    messagingSenderId: '480367101608',
    projectId: 'gymbite',
    authDomain: 'gymbite.firebaseapp.com',
    storageBucket: 'gymbite.firebasestorage.app',
    measurementId: 'G-2BLEB19198',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4U_M7HsyF6RIPPq-R-rgQU5_29h5qmik',
    appId: '1:480367101608:android:e280049a5cc3657c16649d',
    messagingSenderId: '480367101608',
    projectId: 'gymbite',
    storageBucket: 'gymbite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIxa1yRPaSJw-WUjTcF0xPebtfh_HnhXs',
    appId: '1:480367101608:ios:1c65a5133d57ca6a16649d',
    messagingSenderId: '480367101608',
    projectId: 'gymbite',
    storageBucket: 'gymbite.firebasestorage.app',
    iosBundleId: 'com.nomdevs.gymBite',
  );
}
